version: '3.7'

services:
  mysql:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql:rw

  postgres:
    image: postgres:13.6-alpine
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres:/var/lib/postgresql/data:rw

volumes:
  mysql:
  postgres:
