version: '3.7'

services:
  mysql:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
